<a href="https://colab.research.google.com/github/rajkumarshahu/AI-Colab/blob/main/RajShahu_Assignment_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **<center>Assignment #3 <br>SFWRTECH 4AI3:Artificial Intelligence**
**<center>|| <br> ||<br> ||**
**<center>Submitted by: Raj Kumar Shahu (ID: 400426052) <br> Date: October 11, 2023<br>**

In [40]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import log_loss

In [41]:
# Load the Titanic dataset
train_data = pd.read_csv('train.csv')
train_data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S


### Data Preprocessing

1. Handle missing values in the Age column.
2. Encode the Sex column to convert it from categorical to numerical.
3. Split the data into training (first 200 samples) and testing sets (samples 201 to 240).

In [42]:
# Handle missing values in the Age column by filling with mean
train_data['Age'].fillna(train_data['Age'].mean(), inplace=True)

# Encode the Sex column
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
train_data['Sex_encoded'] = encoder.fit_transform(train_data['Sex'])

# Split the data into training and testing sets
train_subset = train_data.iloc[:200]
test_subset = train_data.iloc[200:240]

# Extract relevant columns
X_train_age = train_subset[['Age']]
X_train_gender = train_subset[['Sex_encoded']]
X_train_both = train_subset[['Age', 'Sex_encoded']]
y_train = train_subset['Survived']

X_test_age = test_subset[['Age']]
X_test_gender = test_subset[['Sex_encoded']]
X_test_both = test_subset[['Age', 'Sex_encoded']]
y_test = test_subset['Survived']

X_train_age.shape, X_train_gender.shape, X_train_both.shape

((200, 1), (200, 1), (200, 2))


### 1) Model Construction

#### **Add a part to the program so that both age and gender are considered as the input variables (features). Construct the logistic regression model and estimate the parameters of the log odd function using the first 200 data points. Print the parameters of the model.**

In [43]:
# Model using only Age as a feature
model_age = LogisticRegression()
model_age.fit(X_train_age, y_train)

# Model using only Gender as a feature
model_gender = LogisticRegression()
model_gender.fit(X_train_gender, y_train)

# Model using both Age and Gender as features
model_both = LogisticRegression()
model_both.fit(X_train_both, y_train)
print("\n====================================================================\n")
print("Parameters for model with 'Age' as feature:")
print("Intercept:", model_age.intercept_)
print("Coefficients:", model_age.coef_)
print("\n====================================================================")

print("\nParameters for model with 'Gender' as feature:")
print("Intercept:", model_gender.intercept_)
print("Coefficients:", model_gender.coef_)

print("\n====================================================================")
print("\nParameters for model with both 'Age' and 'Gender' as features:")
print("Intercept:", model_both.intercept_)
print("Coefficients:", model_both.coef_)
print("\n====================================================================")

====================================================================

Parameters for model with 'Age' as feature:
Intercept: [-0.09143047]
Coefficients: [[-0.01978554]]

====================================================================

Parameters for model with 'Gender' as feature:
Intercept: [0.77185337]
Coefficients: [[-2.44157292]]

====================================================================

Parameters for model with both 'Age' and 'Gender' as features:
Intercept: [1.16353306]
Coefficients: [[-0.01458039 -2.41845782]]

====================================================================


### 2 Model Evaluation

#### **Calculate the value of the log-loss function in this case for the sample points 201 to 240. Print the values of the log-loss function (average of the penalty for these 40 samples) for the three models constructed so far, that is, the model consider only age as feature, the model considers only gender as feature, and the model considers both of them as features.**

In [44]:
# Predict probabilities for each model
y_pred_prob_age = model_age.predict_proba(X_test_age)
y_pred_prob_gender = model_gender.predict_proba(X_test_gender)
y_pred_prob_both = model_both.predict_proba(X_test_both)

# Compute log-loss for each model
log_loss_age = log_loss(y_test, y_pred_prob_age)
log_loss_gender = log_loss(y_test, y_pred_prob_gender)
log_loss_both = log_loss(y_test, y_pred_prob_both)

print("\nLog-Loss for model with 'Age' as feature:", log_loss_age)
print("\n===============================================================================\n")
print("Log-Loss for model with 'Gender' as feature:", log_loss_gender)
print("\n===============================================================================\n")
print("Log-Loss for model with both 'Age' and 'Gender' as features:", log_loss_both)

Log-Loss for model with 'Age' as feature: 0.628601218998456

===============================================================================

Log-Loss for model with 'Gender' as feature: 0.5379023121406616

===============================================================================

Log-Loss for model with both 'Age' and 'Gender' as features: 0.5335879176520497


### 3) Conclusion

####**Which one is the most accurate one? (Add you answer as a text box to the program).**

We know that, lower values of log-loss indicate better performance.

- The model considering only the Age feature has the highest log-loss, making it the least accurate.
- The model considering both Age and Gender as features has the lowest log-loss, making it the most accurate.
- The model considering only the Gender feature also performs well, with a log-loss value close to the combined model.

**Hence, the most accurate model is the one that considers both Age and Gender as features.**